/**
 * Created by huangwx on 12/04/2017.
 */

export const GO_TO_HOME = 'GO_TO_HOME'
export const GO_TO_LOGIN = 'GO_TO_LOGIN'

export const GET_ROOM_LIST = 'GET_ROOM_LIST'

export const USER_LOGIN_DOING = 'USER_LOGIN_DOING'
export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR'
export const SET_NEW_ROOM_ID = 'SET_NEW_ROOM_ID'

export const GO_TO_ROOM_INFO = 'GO_TO_ROOM_INFO'
export const GET_ROOM_INFO = 'GET_ROOM_INFO'
export const GO_TO_USER = 'GO_TO_USER'
export const GET_USER = 'GET_USER'
export const GO_TO_ROOM_DETAIL = 'GO_TO_ROOM_DETAIL'
export const GET_ROOM_DETAIL = 'GET_ROOM_DETAIL'
export const SET_ROOM_MESSAGES = 'SET_ROOM_MESSAGES'
export const SET_EDIT_STATUS = 'SET_EDIT_STATUS'
export const SET_USER_DISLIKES = 'SET_USER_DISLIKES'

export const SEND_MESSAGE = 'SEND_MESSAGE'
export const SET_LOADING = 'SET_LOADING'
export const SET_COMMON_DATA = 'SET_COMMON_DATA'

export const EDIT_USER_INFO = 'EDIT_USER_INFO'
export const GET_USER_INFO = 'GET_USER_INFO'

export const GET_LATEST_ROOM_LIST = 'GET_LATEST_ROOM_LIST'
export const GET_WORLD_ROOM_LIST = 'GET_WORLD_ROOM_LIST'
export const GET_RECOMMEND_ROOM_LIST = 'GET_RECOMMEND_ROOM_LIST'
export const GET_TOP_ROOM_LIST = 'GET_TOP_ROOM_LIST'
export const GET_POSTERS = 'GET_POSTERS'


export const GET_INITIAL_LABELS = 'GET_INITIAL_LABELS'

export const ADD_LABEL = 'ADD_LABEL'
export const REMOVE_LABEL = 'REMOVE_LABEL'
export const SET_NEW_ROOM_DATA = 'SET_NEW_ROOM_DATA'

export const GET_QUESTIONNAIRES = 'GET_QUESTIONNAIRES'
export const GET_PARTICIPANTS = 'GET_PARTICIPANTS'

export const MARK_ROOM = 'MARK_ROOM'
export const UNMARK_ROOM = 'UNMARK_ROOM'

export const SIGN_UP = 'SIGN_UP'

export const SET_CHANNELS = 'SET_CHANNELS'
