export const SOCKET_CHANNEL_RECONNECT = 'SOCKET_CHANNEL_RECONNECT'
export const GET_DEVICE_TOKEN = 'GET_DEVICE_TOKEN'
export const GET_ROOM_ID = 'GET_ROOM_ID'

export const CHECK_SOCKET_CONNECT_STATUS = 'CHECK_SOCKET_CONNECT_STATUS'
export const SOCKET_CONNECT_ERROR = 'SOCKET_CONNECT_ERROR'

export const CHECK_SOCKET_RECONNECT = 'CHECK_SOCKET_RECONNECT'
