export const RESET_TO_LOGIN = 'RESET_TO_LOGIN'
export const RESET_TO_HOME = 'RESET_TO_HOME'

export const GO_BACK = 'GO_BACK'

export const NAVIGATE_TO_ROOM_INFO = 'NAVIGATE_TO_ROOM_INFO'
export const NAVIGATE_TO_ROOM_DETAILS = 'NAVIGATE_TO_ROOM_DETAILS'
export const NAVIGATE_TO_USER_INFO = 'NAVIGATE_TO_USER_INFO'
export const NAVIGATE_TO_REGISTER = 'NAVIGATE_TO_REGISTER'
export const NAVIGATE_TO_REGISTERINFO = 'NAVIGATE_TO_REGISTERINFO'
export const NAVIGATE_TO_CHANNELPAGE = 'NAVIGATE_TO_CHANNELPAGE'
export const NAVIGATE_TO_FIND_PASSWORD = 'NAVIGATE_TO_FIND_PASSWORD'
