export const SET_ROOM_INFO = 'SET_ROOM_INFO'
export const SET_ROOM_INFO_JOINED = 'SET_ROOM_INFO_JOINED'
export const SET_ROOM_INFO_MARKED = 'SET_ROOM_INFO_MARKED'
export const SET_ROOM_INFO_DATA = 'SET_ROOM_INFO_DATA'
export const CLEAR_ROOM_INFO = 'CLEAR_ROOM_INFO'

export const JOIN_ROOM = 'JOIN_ROOM'
export const LEAVE_ROOM = 'LEAVE_ROOM'
export const MARK_ROOM = 'MARK_ROOM'
export const UNMARK_ROOM = 'UNMARK_ROOM'

export const FETCH_ROOM_INFO = 'FETCH_ROOM_INFO'

export const FOLLOW_OR_UNFOLLOW_USER = 'FOLLOW_OR_UNFOLLOW_USER'
export const FOLLOW_OR_UNFOLLOW_SUCCESS = 'FOLLOW_OR_UNFOLLOW_SUCCESS'
