export const SET_MY_USER_INFO = 'SET_MY_USER_INFO'

export const PUT_MY_USER_INFO = 'PUT_MY_USER_INFO'
export const FETCH_MY_USER_INFO = 'FETCH_MY_USER_INFO'
export const FETCH_MY_USER_INFO_SUCCESS = 'FETCH_MY_USER_INFO_SUCCESS'
