export const ADD_LABEL = 'ADD_LABEL'
export const REMOVE_LABEL = 'REMOVE_LABEL'
export const SET_NEW_ROOM_DATA = 'SET_NEW_ROOM_DATA'
export const SET_NEW_ROOM_ID = 'SET_NEW_ROOM_ID'
export const CLEAR_NEW_ROOM_DATA = 'CLEAR_NEW_ROOM_DATA'

export const CREATE_NEW_ROOM_REQUEST = 'CREATE_NEW_ROOM_REQUEST'
export const SET_CREATING = 'SET_CREATING'
