export const CLIENT_SET = 'CLIENT_SET'
export const CLIENT_UNSET = 'CLIENT_UNSET'

export const SET_INITIAL_LABELS = 'SET_INITIAL_LABELS'
export const SET_ALERT = 'SET_ALERT'

export const INITIAL_WEBSOCKET = 'INITIAL_WEBSOCKET'
