export const CLIENT_SET = 'CLIENT_SET'
export const CLIENT_UNSET = 'CLIENT_UNSET'

export const SET_INITIAL_LABELS = 'SET_INITIAL_LABELS'
export const SET_ALERT = 'SET_ALERT'
export const SET_ALERT_MESSAGE = 'SET_ALERT_MESSAGE'

export const INITIAL_WEBSOCKET = 'INITIAL_WEBSOCKET'
export const FOLLOW_USER = 'FOLLOW_USER'
export const UNFOLLOW_USER = 'UNFOLLOW_USER'

export const SET_ROOM_MESSAGE = 'SET_ROOM_MESSAGE'
export const RESET_UNREAD_MESSAGE = 'RESET_UNREAD_MESSAGE'

export const SEND_MESSAGE = 'SEND_MESSAGE'
export const SET_SEND_MESSAGE = 'SET_SEND_MESSAGE'
export const SET_DEVICE_TOKEN = 'SET_DEVICE_TOKEN'
export const POST_UNREAD_COUNT = 'POST_UNREAD_COUNT'

export const POST_DEVICE_TOKEN = 'POST_DEVICE_TOKEN'
export const LOGOUT_DEVICE_TOKEN = 'LOGOUT_DEVICE_TOKEN'

export const SET_SOCKET_CONNECT_STATUS = 'SET_SOCKET_CONNECT_STATUS'
export const SET_SOCKET_RECONNECT = 'SET_SOCKET_RECONNECT'
export const SET_MESSAGE_FAILED = 'SET_MESSAGE_FAILED'
