export const CLIENT_SET = 'CLIENT_SET'
export const CLIENT_UNSET = 'CLIENT_UNSET'

export const SET_INITIAL_LABELS = 'SET_INITIAL_LABELS'
export const SET_ALERT = 'SET_ALERT'
export const SET_ALERT_MESSAGE = 'SET_ALERT_MESSAGE'

export const INITIAL_WEBSOCKET = 'INITIAL_WEBSOCKET'
export const FOLLOW_USER = 'FOLLOW_USER'
export const UNFOLLOW_USER = 'UNFOLLOW_USER'

export const SET_ROOM_MESSAGE = 'SET_ROOM_MESSAGE'
export const RESET_UNREAD_MESSAGE = 'RESET_UNREAD_MESSAGE'

export const SEND_MESSAGE = 'SEND_MESSAGE'
export const SET_DEVICE_TOKEN = 'SET_DEVICE_TOKEN'
